describe('Ask Me Anything', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
  })

  it('Should render the correct elements', () => {
    cy.get('h1')
      .should('have.text', 'ASK ME ANYTHING!')
      .get('img')
      .should('have.attr', 'src', '/static/media/robot.096015040b0f160a5871.png')
      .get('.intro')
      .should('contain', 'Nice to meet you.')
      .get('label')
      .should('have.text', 'YOUR QUERY:')
      .get('textarea')
      .should('attr', 'placeholder')
      .should('contain', 'ex: What is the airspeed velocity of a coconut-laden swallow?')
      .get('button')
      .first()
      .should('have.text', 'Ideas!')
      .get('button')
      .eq(1)
      .should('have.text', 'Ask Me!')
      .get('button')
      .eq(2)
      .should('have.text', 'Even More Ideas!')
      .get('h2')
      .should('have.text', 'Our Conversations')
      .get('.conversation-request')
      .should('have.text', `We haven't chatted yet. Please, ask me something.`)
  })

  it('Should display the correct information to the user when the Ideas and Inspiration buttons are clicked', () => {
    cy.get('button')
      .first()
      .click()
      .get('.modal-message')
      .should('exist')
      .should('contain', 'Ideas')
      .get('button')
      .click()
      .get('button')
      .last()
      .click()
  })

  it('Should allow a user to type a question, submit the question, and view the API response', () => {
    cy.intercept('POST', 'https://api.openai.com/v1/engines/text-curie-001/completions',
      { fixture: 'poem.json' }).as('poem')

    cy.get('textarea')
      .type('Do you like poems?')
      .get('.ask-button')
      .click()
      .wait(400)
      .get('.card')
      .should('exist')
      .get('.question')
      .should('have.text', 'Do you like poems?')
      .get('.answer')
      .should('have.text', '\n\nI love poems\n\nYes I do\n\nI love poems\n\nHow about you?')
  })

  it('Should display the most recent query and response first, before any older requests', () => {
    cy.get('textarea')
      .type('What do apples taste like?')
      .get('.ask-button')
      .click()
      .wait(400)
      .get('textarea')
      .type('What is your favorite color?')
      .get('.ask-button')
      .click()
      .wait(400)
      .get('.question')
      .eq(0)
      .should('have.text', 'What is your favorite color?')
      .get('.question')
      .eq(1)
      .should('have.text', 'What do apples taste like?')
  })
})